name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libraries
      run: sudo apt install expect libmcrypt-dev libtdb-dev
    - name: configure
      run: cd src && ./configure --prefix=/usr/local
    - name: make
      run: cd src && make
    - name: test
      run: cd tests && ./setup.exp localhost admin password
